<?php

/**
 * @file
 * Implementations of hooks.
 */

use Drupal\Core\Plugin\Context\EntityContext;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_preprocess_hook().
 */
function ui_patterns_ds_preprocess_field__component(&$vars) {
  $ds_config = $vars['ds-config'];
  if (!empty($ds_config['settings'])) {
    $vars['component'] = [
      '#type' => 'component',
      '#component' => $ds_config['settings']['component_id'] ,
      '#ui_patterns' => $ds_config['settings'],
    ];
  }
}

/**
 * Implements hook_preprocess_ds_entity_view().
 */
function ui_patterns_ds_preprocess_ds_entity_view(&$variables) {
  if (isset($variables['content']) && isset($variables['content']['#entity']) &&
    (isset($variables['content']['#source_contexts']) || isset($variables['content']['#ui_patterns'])) &&
    isset($variables['content']['#entity']) && ($variables['content']['#entity'] instanceof EntityInterface)) {
    if (!isset($variables['content']['#source_contexts'])) {
      $variables['content']['#source_contexts'] = [];
    }
    $variables['content']['#source_contexts']['entity'] = EntityContext::fromEntity($variables['content']['#entity']);
  }
}
